site_name: Made4Net Documentation
site_url: https://made4nethelp.github.io/Made4NetDocumentation/
nav:
  - SSL Certificate: 
      - IIS HTTPS Configuration: sslcertificate/certificateInstallationSteps.md
  - File Imports: 
      - File Importer Troubleshoot: FileImporter.md
  - Schedulers:
      - ViewToTable Scheduler: schedulers/view-to-table-scheduler.md
  - Data Editors:
      - Expressions using functions: DataTables/dtExpressions.md
      - Expressions using Views : DataTables/sku_onpropertychange_po.md
      - DT Property on multiple warehouses : DataTables/dt-use-dt-connection.md  
theme: 
    name: readthedocs
    primary : red
  
extra_css:
  - style.css