site_name: Made4Net Documentation
site_url: https://sitename.example
nav:
  - Home: index.md
  - About: about.md
  - Troubleshooting: Troubleshooting.md
  - File Importer Troubleshoot: FileImporter.md
  - Schedulers:
      - ViewToTable Scheduler: schedulers/view-to-table-scheduler.md
theme: 
    name: readthedocs
    primary : red
  
extra_css:
  - style.css