site_name: Made4Net Documentation
site_url: https://made4nethelp.github.io/Made4NetDocumentation/
nav:
  - Configuration: 
      - IIS HTTPS Configuration: configuration/certificateInstallationSteps.md
      - Timeout Error: configuration/server-disconnection-max-pool.md
      - QR String Configuration: configuration/QRStringConfig.md
      - AWS S3 File Transfer: configuration/aws-s3-file-transfer.md
  - File Imports: 
      - File Importer Troubleshoot: FileImporter.md
      - File Import From Workstation: FileImports/FileImportfromWS.md     
  - Schedulers:
      - ViewToTable Scheduler: schedulers/view-to-table-scheduler.md
      - Force User Logout: schedulers/force-user-logout.md
  - Data Editors:
      - Expressions using functions: DataTables/dtExpressions.md
      - Expressions using Views : DataTables/sku_onpropertychange_po.md
      - DT Property on multiple warehouses : DataTables/dt-use-dt-connection.md
  - SCExpert Release Notes:
      - 4.12.1.x : ReleaseNotes/4.12.1.x.md
  - Troubleshooting:
      - Nuget Reference Error: troubleshooting/nuget-reference.md  
  - Create Load Importer:
      - Create Load Importer: LoadImporter/LoadImporter.md
  - Fedex Integration:
      - Fedex Integration: FedXIntegration/fedexIntegration_notes_v1.md
  - UPS Integration:
      - UPS Integration: FedXIntegration/UPSIntegration notes_v1.md
    
theme: 
    name: readthedocs
    primary : red
  
extra_css:
  - style.css
